pipeline {
    agent any
    stages {
        stage('stage 1') {
            steps {
                echo 'Hello world!'
                bat 'python --version'

            }
        }
        stage('Test') {
            steps {
                script {
                    try {
                        bat 'python test\\code\\unit_test_A.py'
                    } catch (Exception e) {
                        echo 'Exception occurred: ' + e.toString()
                    }
                }
                bat 'bandit -r test\\code\\dodatak_A.py'
            }
        }
        stage('Clear') {
            steps {
                bat 'rmdir /s /q test'


            }
        }
        
    }
}