pipeline {
    agent any
    environment { 
        SUCCESS = '1'
    }
    stages {
        stage('Test') {
            steps {
                script {
                    try {
                        bat 'python test\\code\\unit_test_A.py 2> "logs\\unit_test_%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%_%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%%TIME:~9,2%.txt"'
                    } catch (Exception e) {
                        echo 'TEST FAILED! Check logs for more info'
                        echo 'Exception occurred: ' + e.toString()
                        SUCCESS = '0'
                    }
                }
            }
        }
        stage('Security Test') {
            steps {
                script {
                    try {
                        bat 'bandit -r test\\code\\dodatak_A.py -f json -o "logs\\bandit_test_%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%_%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%%TIME:~9,2%.json"'
                    } catch (Exception e) {
                        echo 'SECURITY TEST FAILED! Check logs for more info'
                        echo 'Exception occurred: ' + e.toString()
                        SUCCESS = '0'
                    }
                }
            }
        }
        stage('Deliver') {
            steps {
                script{
                    if(SUCCESS == '1') {
                        bat 'xcopy /s /e /v /Q /Y test\\ production\\'
                    }
                }
            }
            post {
                always {
                    bat 'rmdir /s /q test'
                }
            }
        }

        
    }
}