pipeline {
    agent any
    stages {
        stage('stage 1') {
            steps {
                echo 'Hello world!'
                bat 'python --version'
                bat 'mkdir test'
            }
        }
        stage('Clone') {
            steps {
                bat 'cd test'
                git url: 'https://github.com/d-strunjak/sosa-lab3.git'
                bat 'git checkout main'
                bat 'dir'

            }
        }
    }
}